openapi: 3.0.0
info:
  description: Swagger doc for Stargate
  title: stargate AOI external API
  contact:
    name: Team-Identity
    email: identity@pixxel.co.in
  version: v0.1.0
servers:
- url: https://api.pixxel.space
tags:
- name: external
paths:
  /ping:
    get:
      description: Returns a pong message.
      tags:
      - external
      summary: Ping Server
      responses:
        '200':
          description: Successful ping
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
